language: rust
cache:
  - apt
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      addons:
        apt:
          - libclang-dev
          - libftdi1-dev
    - env: TARGET=thumbv6m-none-eabi
    - env: TARGET=thumbv7em-none-eabi
    - env: TARGET=thumbv7em-none-eabihf
    - env: TARGET=thumbv7m-none-eabi
install:
  - rustup target add $TARGET
script:
  - |
    if [ $TARGET = "x86_64-unknown-linux-gnu" ]; then
      cargo test --verbose
      cargo doc --verbose
    fi
  - cargo build --target $TARGET --verbose --release
notifications:
  email:
    on_success: never
